export const ROLES = [
  "human",
  "architect",
  "supervisor",
  "developer",
  "reviewer",
  "integrator",
  "memory_consolidator",
] as const;

export type Role = (typeof ROLES)[number];

export const CAPABILITIES = [
  "graph.read",
  "graph.write",
  "audit.write",
  "task.claim",
  "task.assign",
  "task.close",
  "provider.comment",
  "provider.issue.update",
  "provider.issues.create",
  "provider.issues.update",
  "provider.issues.comment",
  "provider.issues.addLabel",
  "provider.issues.removeLabel",
  "provider.epics.create",
  "provider.epics.update",
  "provider.epics.close",
  "provider.branch.push",
  "provider.branches.push",
  "provider.branches.protect",
  "provider.mr.open",
  "provider.mr.approve",
  "provider.mr.merge",
  "provider.mr.comment",
  "provider.mr.review_thread",
  "provider.commits.read",
  "provider.pipelines.read",
  "provider.pipelines.trigger",
  "memory.candidate.write",
  "memory.write",
  "decision.write",
  "sandbox.exec",
  "tool.call",
  "release.deploy",
  "policy.override",
  "provider.admin.bootstrap",
] as const;

export type Capability = (typeof CAPABILITIES)[number];
