GITLAB_BASE_URL: ENC[AES256_GCM,data:g3Sy61/ZJuIFF8DlQ268V8Vm1B08B15KKpd8,iv:/GmY7hru/f6aVmu4S9Ahn6pwgy1Yuzrnn3cVr0kq5LE=,tag:s4mhZRaKcfpA1cekHLS1JQ==,type:str]
GITLAB_TOKEN: ENC[AES256_GCM,data:vVo2L6jJVHv7AbcK462ooWC6mE0zOU4IZ8dFSyn5660f28mN5fPb/gLG55dJ7s7mcOKjsJs=,iv:Fq00+BFP/RmfxGqooOThLh6KCoCdmA55u7gYgn67FAg=,tag:Gr+ljq8YoVX1SHypn070iw==,type:str]
sops:
    hc_vault:
        - vault_address: https://bao.home.shdr.ch
          engine_path: colony
          key_name: sops
          created_at: "2026-04-25T15:32:37Z"
          enc: vault:v1:jL/yMr6es851zSWHS/93vkRPzexnnTFjv3WvWcEGBrCRvys5WlkGUvElxVmHLPwvsD6C6G6FYgdHx6Nl
    lastmodified: "2026-04-25T16:00:38Z"
    mac: ENC[AES256_GCM,data:89SLjW5Fch75/umNhG8+BXjW+/o8RGHL5Axs4SoQmZES4M1tB6ou/f3iy1FDDSHTnYV1n0xtVLXokMRgZJQvHOacP1piyzgUvjHJP0/nE6SPUIhuDglzY4H05Yaa+0fzZrqPYPqbqtf/5ICm/BnZKkMmCytsBEb21z+o0MAdg3c=,iv:jzdEkLCcDE7cZaXg20QwWRbi1JhP4gL3r5CEIWxT6tw=,tag:2qTwKY4neEPwqobz/M/k7Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
