GITLAB_BASE_URL: ENC[AES256_GCM,data:g3Sy61/ZJuIFF8DlQ268V8Vm1B08B15KKpd8,iv:/GmY7hru/f6aVmu4S9Ahn6pwgy1Yuzrnn3cVr0kq5LE=,tag:s4mhZRaKcfpA1cekHLS1JQ==,type:str]
GITLAB_TOKEN: ENC[AES256_GCM,data:w2qLAKlCFfAl4vO0RWMDk6H2bV5ELEKWCR0HMt43zTvJKkGNrDhtg00wpbjb8w/IyZsE,iv:PqEk2BB+Kyl7KQhStqmVTK5h2/uKkjisuW3mZcFhX38=,tag:TmMURKaL90ihIjrE5JIauQ==,type:str]
sops:
    hc_vault:
        - vault_address: https://bao.home.shdr.ch
          engine_path: colony
          key_name: sops
          created_at: "2026-04-25T15:32:37Z"
          enc: vault:v1:jL/yMr6es851zSWHS/93vkRPzexnnTFjv3WvWcEGBrCRvys5WlkGUvElxVmHLPwvsD6C6G6FYgdHx6Nl
    lastmodified: "2026-04-25T15:32:37Z"
    mac: ENC[AES256_GCM,data:VLkPNXTpa4cuqWjFPi+BDoXkxRieW20A1CL3NDERVy6leu15lrt4lds7wKZHW0zT3erEaX2c9+YnU7ibrKxHUq+QM3SqYtHtzBDt/YP1qBN9mrfKBOBZruOj1T7s3sprmdG9R3Sy6TXjMw7cZesibf/UbttPr0PuusV7OK4J4ZI=,iv:w/6F0huS1hjuxAvSFGFhdl06C2t9HfDhoidixDQnY3g=,tag:Miuqb+KRau85LbhBeGJoiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
